name: utsav
description: Utsav Fasion Application

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  validators: ^3.0.0
  carousel_slider: ^4.2.1
  flutter_staggered_animations: ^1.1.1
  smooth_page_indicator: ^1.0.0+2
  dotted_border: ^2.0.0+3
  roundcheckbox: ^2.0.5
  select_form_field: ^2.2.0
  bottom_drawer: ^0.0.5
  http:
  flutter_pannable_rating_bar: ^2.5.1+2
  email_validator: ^2.1.17
  photo_view: ^0.14.0
#  change_app_package_name: ^1.1.0
  shared_preferences: ^2.0.20
  flutter_bloc: ^8.1.2
  dio: ^5.1.1
  geocoding: ^2.1.0
  geolocator: ^9.0.2
  flutter_styled_toast: ^2.1.3
  vibration: ^1.7.6
  shimmer: ^2.0.0
  cached_network_image: ^3.2.3
  country_provider2: ^1.0.2+4
  crypto: ^3.0.0
  xml2json: ^5.3.6
  webview_flutter: ^2.1.1
  html: ^0.15.3
#  webview_flutter: ^4.2.0
  flutter_inappwebview: ^5.7.2+3
  flutter_lints: ^2.0.1
  build_runner:
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1
  amazon_payfort: ^0.0.8
  network_info_plus: ^2.2.0
  provider: ^6.0.3
  badges: ^3.1.1
  flutter_paypal: ^0.0.8
  paytm_allinonesdk: ^1.2.1
  cc_avenue: ^1.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  #  flutter_launcher_icons: "^0.12.0"
  #
  #flutter_icons:
  #  android: "launcher_icon"
  #  ios: true
  #  image_path: "assets/icon/icon.png"
  #  min_sdk_android: 21
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0



flutter:

  uses-material-design: true


  assets:
    - images/
  #   - images/a_dot_ham.jpeg


  fonts:
    - family: NotoSans
      fonts:
        - asset: font/Inter/NotoSans-Regular.ttf
    #        - asset: font/Inter/Inter-ExtraBold.ttf
    #        - asset: font/Inter/Inter-ExtraLight.ttf
    #        - asset: font/Inter/Inter-Light.ttf
    #        - asset: font/Inter/Inter-Medium.ttf
    #        - asset: font/Inter/Inter-Regular.ttf
    #        - asset: font/Inter/Inter-SemiBold.ttf
    #        - asset: font/Inter/Inter-Thin.ttf

    - family: SourceSansPro
      fonts:
        - asset: font/Inter/SourceSansPro-Regular.ttf
    - family: Taviraj
      fonts:
        - asset: font/Inter/Taviraj-Regular.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

